### ISSUE TITLE
dependency of packages in questionclassifier

### ISSUE THREAD

**Issue by anupamme** [stanfordnlp/chirpycardinal#19]
While installing the package I am running into some package conflicts 

e.g. when I run the following (in an isolated virtualenv):

I am using python3.7 on macOS.

pip3 install -r docker/questionclassifier/app/requirements.txt

I get the following errors:
ERROR: pytorch-ignite 0.4.4 has requirement torch<2,>=1.3, but you'll have torch 1.1.0 which is incompatible.
ERROR: transformers 4.5.0 has requirement numpy>=1.17, but you'll have numpy 1.16.4 which is incompatible.
ERROR: pyarrow 3.0.0 has requirement numpy>=1.16.6, but you'll have numpy 1.16.4 which is incompatible.
ERROR: pandas 1.2.3 has requirement numpy>=1.16.5, but you'll have numpy 1.16.4 which is incompatible.
ERROR: datasets 1.5.0 has requirement numpy>=1.17, but you'll have numpy 1.16.4 which is incompatible.
ERROR: datasets 1.5.0 has requirement tqdm<4.50.0,>=4.27, but you'll have tqdm 4.60.0 which is incompatible.
ERROR: scipy 1.6.2 has requirement numpy<1.23.0,>=1.16.5, but you'll have numpy 1.16.4 which is incompatible.
ERROR: jsonschema 3.2.0 has requirement six>=1.11.0, but you'll have six 1.10.0 which is incompatible.
ERROR: wandb 0.10.25 has requirement six>=1.13.0, but you'll have six 1.10.0 which is incompatible.
ERROR: torchvision 0.9.1 has requirement torch==1.8.1, but you'll have torch 1.1.0 which is incompatible.

I believe similar conflicts in python packages are present in other docker images as well.

Can you guide how to get around these errors? 
I can remove all the version numbers in the requirements.txt and then it works fine but the docker image does not return response to curl commands as pointed out in another issue.

**Comment by AshwinParanjape** [comment]
You are right, there are issues in the package dependencies. We didn't freeze them while building, so that we keep getting the upgrades. But then transformers often introduces breaking changes. And that's probably why after you remove all the version numbers it installs latest huggingface which breaks the python code. One thing you could try is to fix the huggingface and pytorch version numbers, but remove all others. 

Alternatively, I'm working on hosting all of our docker images on dockerhub. It'll take some time to upload them all, but that might make it much easier to deploy for everyone. And they won't run into this issue unless they are planning to update any of the docker images.

**Comment by anupamme** [comment]
I tried tinkering with the version numbers and was able to get around these errors. I am attaching them below (for anyone else who would want a reference).

But the docker image was not responding to my curl commands so the only way for me is to debug them using their logs.

I was just curious what is the timeline you are going to put the images on the docker hub? 

Is it okay that we keep this issue open and close it once you have uploaded the images?

Flask==0.11.1
Flask-RESTful==0.3.5
Werkzeug==0.15.3
future==0.16.0
jsonpickle==0.9.4
numpy==1.17.0
pandoc==1.0.0b2
six==1.13.0
typing==3.6.2
ConfigArgParse==0.12.0
gunicorn==19.7.1
tqdm==4.47
# From convpara/topical_chat/analysis/requirements.txt
pytorch-ignite
transformers
tensorboardX
tensorboard
simpletransformers
torchvision
torch==1.8.1

**Comment by AshwinParanjape** [comment]
Pulling from AWS and pushing to dockerhub is a surprisingly compute intensive activity. So it seems to be taking a while. 
Right now I've uploaded the largest and trickiest images: convpara and gpt2ed here
`docker pull openchirpy/gpt2ed`
`docker pull openchirpy/convpara`

I'll post the remaining images as they get uploaded. Thanks for the patience.

**Comment by AshwinParanjape** [comment]
If the docker images still don't work, feel free to re-open this or create a new issue.
