### ISSUE TITLE
docker images for all annotators

### ISSUE THREAD

**Issue by anupamme** [stanfordnlp/chirpycardinal#29]
I looked at the docker images which are available at [1]. However, there are a couple of more annotators which are not available at the docker hub, these are:

1. emotionclassifier
2. coref
3. qa
4. sentseg

I see that they are not currently used in the chirpy cardinal bot but I have some use cases for these. And I tried building them from codebase but ran into versioning issues so if you can make these 4 images also available at docker hub that will be great.

1. https://hub.docker.com/u/openchirpy

**Comment by AshwinParanjape** [comment]
All of these images/dockerfiles are deprecated and unmaintained. They haven't been built for more than a year and the images we built then have been wiped by now. I doubt we'll be able rebuild them without much effort. 

It might only be worth putting in the time if you have a specific use case. If you do, let's begin with docker container you want most and we can help you build it. I'll close this issue, but feel free to open another if with a specific docker image and the error you are getting while trying to build it.
