### ISSUE TITLE
Treelet State

### ISSUE THREAD

**Issue by anupamme** [stanfordnlp/chirpycardinal#30]
Here is what I would like to do:

I would like a treelet to remember its state e.g. if a treelet is supposed to do a 2-3 turn conversation. So if this treelet sent an opening question, it needs to know whether the response generator it belongs to was selected among all the response generators. If it was selected, it knows that the user utterance responds to its question otherwise it is not.

So basically the response generator needs to query which response generator was selected in the last round, how can this be done?

If it cannot be done, can you suggest how should it be implemented?

**Comment by ameliahardy** [comment]
Hi!

Response generators should all have two methods: `update_state_if_chosen` and `update_state_if_not_chosen`.  The appropriate method will be called automatically for all response generators, once the response generator for a given turn has been selected by the dialog manager, so you can use them for the functionality you're describing. 

One approach to this would be creating a property of `State` called `asked_question`. You can set `asked_question` to be True in `update_state_if_chosen` and False in `update_state_if_not_chosen`. Then, you can check this property in your treelet to know whether or not the question was asked on the previous turn and the user is now answering it.

For more examples, I'd check out the categories treelet. The `State` class is declared [here](https://github.com/stanfordnlp/chirpycardinal/blob/635957802720467cd4447caa9481ad6152f10bd3/chirpy/response_generators/categories/classes.py) and `update_state_if_chosen`/`update_state_if_not_chosen` are [here](https://github.com/stanfordnlp/chirpycardinal/blob/635957802720467cd4447caa9481ad6152f10bd3/chirpy/response_generators/categories/categories_response_generator.py#L151).

**Comment by anupamme** [comment]
Thank you for the answer. Closing it now.
