### ISSUE TITLE
ModuleNotFoundError: No module named 'agent'

### ISSUE THREAD

**Issue by nghidinhit** [stanfordnlp/chirpycardinal#4]
When i run python3 bin/shell_chat.py, i got this error: ModuleNotFoundError: No module named 'agent'
Please help me!.

**Comment by AshwinParanjape** [comment]
Can you try after adding the repo/project directory to PYTHONPATH? 

Alternatively, could you try pulling the branch `https://github.com/stanfordnlp/chirpycardinal/tree/remote-persistent-agent` and running `python -m servers.local.shell_chat` from the repo/project directory?

The remote-persistent-agent branch has latest refactored code that should work without adding anything to PYTHONPATH.

**Comment by AshwinParanjape** [comment]
The new branch is merged and running `python -m servers.local.shell_chat` should work.
